#!/usr/bin/env node
import { Command } from "commander";
import { registerDoctorCommand } from "./commands/doctor.js";
import { registerInstallCommand } from "./commands/install.js";
import { registerInfoCommand } from "./commands/info.js";
import { registerInitCommand } from "./commands/init.js";
import { registerListCommand } from "./commands/list.js";
import { registerLoginCommand } from "./commands/login.js";
import { registerLogoutCommand } from "./commands/logout.js";
import { registerPublishCommand } from "./commands/publish.js";
import { registerPackCommand } from "./commands/pack.js";
import { registerRemoveCommand } from "./commands/remove.js";
import { registerSearchCommand } from "./commands/search.js";
import { registerValidateCommand } from "./commands/validate.js";
import { registerUpdateCommand } from "./commands/update.js";
import { registerUninstallCommand } from "./commands/uninstall.js";
import { registerInspectCommand } from "./commands/package/inspect.js";
import { registerUnpackCommand } from "./commands/package/unpack.js";
import { registerLintCommand } from "./commands/package/lint.js";
import { registerCacheCommand } from "./commands/system/cache.js";
import { registerConfigCommand } from "./commands/system/config.js";
import { registerRunCommand } from "./commands/run.js";
import { registerTemplateCommand } from "./commands/template.js";
import { registerAgentCommand } from "./commands/agent.js";
import { registerWorkflowCommand } from "./commands/workflow.js";
import { CacheService } from "./services/CacheService.js";
import { ConfigService } from "./services/ConfigService.js";
import { PackageService } from "./services/PackageService.js";
import { RegistryService } from "./services/RegistryService.js";
import { RuntimeService } from "./services/RuntimeService.js";
import { RuntimeRegistry } from "./runtime/RuntimeRegistry.js";
import { RuntimeEngine } from "./runtime/RuntimeEngine.js";
import { WorkflowManager } from "./runtime/WorkflowManager.js";
import { AgentManager } from "./runtime/AgentManager.js";
import { ToolManager } from "./runtime/ToolManager.js";
import { ProviderManager, OpenAIProvider, GeminiProvider, ClaudeProvider, GroqProvider, OllamaProvider } from "./runtime/ProviderManager.js";
import { ConnectorManager } from "./runtime/ConnectorManager.js";
import { MemoryManager } from "./runtime/MemoryManager.js";
import { CheckpointManager } from "./runtime/CheckpointManager.js";
import { EventBus } from "./runtime/EventBus.js";
import { AgentTemplateService } from "./services/AgentTemplateService.js";
import { AgentCompositionValidator } from "./services/AgentCompositionValidator.js";
import { WorkflowGenerator } from "./services/WorkflowGenerator.js";
import { LocalAgentExecutor } from "./services/LocalAgentExecutor.js";
import { toErrorMessage } from "./utils/errors.js";
import { output } from "./utils/output.js";

const program = new Command(); const config = new ConfigService(); const registry = new RegistryService(); const packages = new PackageService(); const cache = new CacheService(); const runtime = new RuntimeService(config, packages);
const runtimeRegistry = new RuntimeRegistry(); const providerManager = new ProviderManager(runtimeRegistry); [new OpenAIProvider(), new GeminiProvider(), new ClaudeProvider(), new GroqProvider(), new OllamaProvider()].forEach((provider) => providerManager.register(provider)); const engine = new RuntimeEngine(runtimeRegistry, new WorkflowManager(runtimeRegistry), new AgentManager(runtimeRegistry), new ToolManager(runtimeRegistry), providerManager, new MemoryManager(), new CheckpointManager(`${config.rootDirectory}\\checkpoints`), new EventBus()); void new ConnectorManager(runtimeRegistry);
const templates = new AgentTemplateService(config); const agentValidator = new AgentCompositionValidator(templates); const workflowGenerator = new WorkflowGenerator();
program.name("kiln").description("KILN CLI\nKnowledge Integration & Lifecycle Network").version("0.1.0").showSuggestionAfterError();
program.hook("preAction", async () => config.initialize());
registerSearchCommand(program, registry); registerInstallCommand(program, config, packages); registerListCommand(program, config); registerRemoveCommand(program, config); registerPublishCommand(program, registry); registerLoginCommand(program, config); registerLogoutCommand(program, config); registerDoctorCommand(program, config); registerInitCommand(program, packages); registerValidateCommand(program, packages); registerPackCommand(program, packages); registerInfoCommand(program, config, packages); registerRunCommand(program, runtime, engine, new LocalAgentExecutor());
registerInspectCommand(program, config, packages); registerUnpackCommand(program, packages); registerLintCommand(program, packages); registerUpdateCommand(program); registerUninstallCommand(program, config); registerCacheCommand(program, config, cache); registerConfigCommand(program, config);
registerTemplateCommand(program, templates); registerAgentCommand(program, templates, agentValidator); registerWorkflowCommand(program, workflowGenerator);
program.parseAsync().catch((error: unknown) => { output.error(toErrorMessage(error)); process.exitCode = 1; });
