#!/usr/bin/env node
import { join } from "node:path";
import { Command } from "commander";
import { registerDoctorCommand } from "./commands/doctor.js";
import { registerInstallCommand } from "./commands/install.js";
import { registerInfoCommand } from "./commands/info.js";
import { registerInitCommand } from "./commands/init.js";
import { registerListCommand } from "./commands/list.js";
import { registerLoginCommand } from "./commands/login.js";
import { registerLogoutCommand } from "./commands/logout.js";
import { registerPublishCommand } from "./commands/publish.js";
import { registerPackCommand } from "./commands/pack.js";
import { registerRemoveCommand } from "./commands/remove.js";
import { registerSearchCommand } from "./commands/search.js";
import { registerValidateCommand } from "./commands/validate.js";
import { registerUpdateCommand } from "./commands/update.js";
import { registerUninstallCommand } from "./commands/uninstall.js";
import { registerInspectCommand } from "./commands/package/inspect.js";
import { registerUnpackCommand } from "./commands/package/unpack.js";
import { registerLintCommand } from "./commands/package/lint.js";
import { registerCacheCommand } from "./commands/system/cache.js";
import { registerConfigCommand } from "./commands/system/config.js";
import { registerRunCommand } from "./commands/run.js";
import { registerLogsCommand } from "./commands/logs.js";
import { registerServeCommand } from "./commands/serve.js";
import { registerTemplateCommand } from "./commands/template.js";
import { registerAgentCommand } from "./commands/agent.js";
import { registerWorkflowCommand } from "./commands/workflow.js";
import { CacheService } from "./services/CacheService.js";
import { ConfigService } from "./services/ConfigService.js";
import { PackageService } from "./services/PackageService.js";
import { RegistryService } from "./services/RegistryService.js";
import { RuntimeRegistry } from "./runtime/RuntimeRegistry.js";
import { AgentRuntime } from "./runtime/AgentRuntime.js";
import { RunRecorder } from "./runtime/RunRecorder.js";
import { ProviderManager, OpenAIProvider, GeminiProvider, ClaudeProvider, GroqProvider, OllamaProvider } from "./runtime/ProviderManager.js";
import { MemoryManager } from "./runtime/MemoryManager.js";
import { EventBus } from "./runtime/EventBus.js";
import { AgentTemplateService } from "./services/AgentTemplateService.js";
import { AgentCompositionValidator } from "./services/AgentCompositionValidator.js";
import { WorkflowGenerator } from "./services/WorkflowGenerator.js";
import { toErrorMessage } from "./utils/errors.js";
import { output } from "./utils/output.js";

const program = new Command(); const config = new ConfigService(); const registry = new RegistryService(); const packages = new PackageService(); const cache = new CacheService();
const runtimeRegistry = new RuntimeRegistry(); const providerManager = new ProviderManager(runtimeRegistry); [new OpenAIProvider(), new GeminiProvider(), new ClaudeProvider(), new GroqProvider(), new OllamaProvider()].forEach((provider) => providerManager.register(provider));
const eventBus = new EventBus(); const agentRuntime = new AgentRuntime(providerManager, new MemoryManager(), eventBus); const runRecorder = new RunRecorder(eventBus, join(config.cacheDirectory, "runs"));
const templates = new AgentTemplateService(config); const agentValidator = new AgentCompositionValidator(templates); const workflowGenerator = new WorkflowGenerator();
program.name("kiln").description("KILN CLI\nKnowledge Integration & Lifecycle Network").version("0.2.0").showSuggestionAfterError();
program.hook("preAction", async () => config.initialize());
registerSearchCommand(program, registry); registerInstallCommand(program, config, packages); registerListCommand(program, config); registerRemoveCommand(program, config); registerPublishCommand(program, registry); registerLoginCommand(program, config); registerLogoutCommand(program, config); registerDoctorCommand(program, config); registerInitCommand(program, packages); registerValidateCommand(program, packages); registerPackCommand(program, packages); registerInfoCommand(program, config, packages); registerRunCommand(program, config, agentRuntime); registerLogsCommand(program, runRecorder); registerServeCommand(program, config, agentRuntime, eventBus, runRecorder);
registerInspectCommand(program, config, packages); registerUnpackCommand(program, packages); registerLintCommand(program, packages); registerUpdateCommand(program); registerUninstallCommand(program, config); registerCacheCommand(program, config, cache); registerConfigCommand(program, config);
registerTemplateCommand(program, templates); registerAgentCommand(program, templates, agentValidator, packages); registerWorkflowCommand(program, workflowGenerator);
program.parseAsync().catch((error: unknown) => { output.error(toErrorMessage(error)); process.exitCode = 1; });
